name = "Mutt Compose"
grammar = "mutt_compose"
path_suffixes = ["eml", "msg"]
line_comments = ["# "]
tab_size = 2
# Match mutt/neomutt compose files by their first line (usually starts with a header)
first_line_pattern = "^(From|To|Subject|Date|Message-ID):"