name = "Muttrc"
grammar = "muttrc"
path_suffixes = ["muttrc", "neomuttrc"]
line_comments = ["# "]
tab_size = 2
hard_tabs = false
# Match config files that start with mutt commands
first_line_pattern = "^(set|bind|source|color|alias|folder-hook|send-hook|save-hook|charset-hook|iconv-hook)"